# Generated by Django 5.2.16 on 2026-07-07 23:16

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_bootstrap_editorial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='contains_identifiable_minors',
            field=models.BooleanField(default=False, help_text='Marca esta opción si la noticia puede identificar a menores por nombre o firma pública, imagen reconocible, voz, video u otra información que haga identificable al menor.', verbose_name='Contiene menores identificables'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='minor_publication_authorizations_verified',
            field=models.BooleanField(default=False, help_text='Declaración operacional del editor. Los documentos de autorización no se almacenan en el CMS en esta versión.', verbose_name='Confirmo que se verificaron las autorizaciones requeridas para exponer públicamente a los menores identificables de esta noticia'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='sensitive_content',
            field=models.BooleanField(default=False, help_text='Señal editorial para contenido social, denuncia u otro tratamiento delicado que merece especial criterio y una firma pública protectora cuando corresponda.', verbose_name='Contenido sensible'),
        ),
        migrations.CreateModel(
            name='ContributorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre interno del grupo, taller o equipo de colaboradores.', max_length=160, verbose_name='Nombre')),
                ('school', models.ForeignKey(help_text='Colegio al que pertenece este grupo interno.', on_delete=django.db.models.deletion.PROTECT, related_name='contributor_groups', to='news.school', verbose_name='Colegio')),
            ],
            options={
                'verbose_name': 'Grupo de colaboradores',
                'verbose_name_plural': 'Grupos de colaboradores',
                'ordering': ['school__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MinorContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nombre completo para trazabilidad editorial interna; no se publica automáticamente.', max_length=160, verbose_name='Nombre interno')),
                ('age_band', models.CharField(choices=[('under_14', 'Menor de 14 años'), ('14_to_17', 'De 14 a 17 años')], help_text='No registrar fecha de nacimiento ni edad exacta.', max_length=16, verbose_name='Franja de edad')),
                ('group', models.ForeignKey(help_text='Grupo interno del colaborador menor.', on_delete=django.db.models.deletion.PROTECT, related_name='minor_contributors', to='news.contributorgroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Colaborador menor',
                'verbose_name_plural': 'Colaboradores menores',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='NewsPagePublicCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('display_name', models.CharField(help_text='Texto público elegido por el editor. No se deriva automáticamente de colaboradores internos, colegios ni usuarios.', max_length=255, verbose_name='Firma pública')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_credits', to='news.newspage')),
            ],
            options={
                'verbose_name': 'Firma pública',
                'verbose_name_plural': 'Firmas públicas',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsPageContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_page_contributions', to='news.minorcontributor', verbose_name='Colaborador menor')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_contributors', to='news.newspage')),
            ],
            options={
                'verbose_name': 'Colaborador interno de noticia',
                'verbose_name_plural': 'Colaboradores internos de noticia',
                'ordering': ['sort_order'],
                'abstract': False,
                'unique_together': {('page', 'contributor')},
            },
        ),
    ]
