# Generated by Django 5.2.16 on 2026-07-09 16:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspage_contains_identifiable_minors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('article_image', 6), ('youtube', 7), ('spotify', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Subtítulo', 'template': 'news/blocks/heading.html'}), 1: ('apps.news.blocks.ParagraphBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Párrafo'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Pie de foto'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe el sentido contextual de esta imagen en la noticia.', 'label': 'Texto alternativo'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Crédito de imagen', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('alt_text', 4), ('credit', 5)]], {}), 7: ('apps.news.blocks.YouTubeEmbedBlock', (), {}), 8: ('apps.news.blocks.SpotifyEmbedBlock', (), {})}, verbose_name='Contenido'),
        ),
    ]
