# Generated by Django 5.2.16 on 2026-07-10 22:49

import json

import wagtail.fields
from django.db import migrations
from django.utils.html import escape


def convert_raw_body(raw_body):
    converted_body = []
    changed = False

    for item in raw_body:
        if not isinstance(item, dict) or item.get("type") != "heading":
            converted_body.append(item)
            continue

        converted_item = item.copy()
        heading_text = item.get("value") or ""
        converted_item["type"] = "paragraph"
        converted_item["value"] = f"<h2>{escape(str(heading_text))}</h2>"
        converted_body.append(converted_item)
        changed = True

    return converted_body, changed


def convert_heading_blocks_to_paragraphs(apps, schema_editor):
    NewsPage = apps.get_model("news", "NewsPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    database_alias = schema_editor.connection.alias

    for page in NewsPage.objects.using(database_alias).iterator():
        converted_body, changed = convert_raw_body(list(page.body.raw_data))

        if changed:
            page.body = converted_body
            page.save(using=database_alias, update_fields=["body"])

    revisions = Revision.objects.using(database_alias).filter(
        content_type__app_label="news",
        content_type__model="newspage",
    )

    for revision in revisions.iterator():
        content = revision.content
        if not isinstance(content, dict):
            continue

        serialized_body = content.get("body")
        if not isinstance(serialized_body, str):
            continue

        raw_body = json.loads(serialized_body)
        if not isinstance(raw_body, list):
            continue

        converted_body, changed = convert_raw_body(raw_body)
        if changed:
            converted_content = content.copy()
            converted_content["body"] = json.dumps(converted_body)
            revision.content = converted_content
            revision.save(using=database_alias, update_fields=["content"])


def reverse_heading_conversion(apps, schema_editor):
    """Do nothing: migrated H2 elements cannot be identified unambiguously."""


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newspage_body'),
    ]

    operations = [
        migrations.RunPython(
            convert_heading_blocks_to_paragraphs,
            reverse_code=reverse_heading_conversion,
        ),
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('article_image', 5), ('youtube', 6), ('spotify', 7)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'blockquote', 'hr', 'document-link'], 'label': 'Párrafo'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Pie de foto'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe el sentido contextual de esta imagen en la noticia.', 'label': 'Texto alternativo'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Crédito de imagen', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alt_text', 3), ('credit', 4)]], {}), 6: ('apps.news.blocks.YouTubeEmbedBlock', (), {}), 7: ('apps.news.blocks.SpotifyEmbedBlock', (), {})}, verbose_name='Contenido'),
        ),
    ]
