# Generated by Django 5.2.16 on 2026-07-15 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newspage_seo_assistant_fields'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='featured_image_alt_text',
            field=models.CharField(blank=True, help_text='Describe el sentido contextual de esta imagen en la noticia.', max_length=500, verbose_name='Texto alternativo'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='featured_image_caption',
            field=models.CharField(blank=True, max_length=500, verbose_name='Pie de foto'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='featured_image_credit',
            field=models.CharField(blank=True, help_text='Opcional. Indica la fuente o autoría pública de la imagen.', max_length=255, verbose_name='Crédito de imagen'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='og_image_alt_text',
            field=models.CharField(blank=True, help_text='Describe el sentido contextual de esta imagen en la noticia.', max_length=500, verbose_name='Texto alternativo'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='og_image_caption',
            field=models.CharField(blank=True, max_length=500, verbose_name='Pie de foto'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='og_image_credit',
            field=models.CharField(blank=True, help_text='Opcional. Indica la fuente o autoría pública de la imagen.', max_length=255, verbose_name='Crédito de imagen'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Selecciona el archivo principal. Completa debajo su metadata editorial para esta noticia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen destacada'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Si queda vacía, se usa la imagen destacada y su texto alternativo contextual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen para redes sociales'),
        ),
    ]
