# Generated by Django 5.2.16 on 2026-07-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0009_reconcile_mvp_access"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspage",
            name="summary",
        ),
        migrations.AlterField(
            model_name="newspage",
            name="og_description",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Si queda vacía, se usa la descripción meta. Si ambas están "
                    "vacías, se omite la descripción social."
                ),
                max_length=500,
                verbose_name="Descripción para redes sociales",
            ),
        ),
    ]
