# Generated by Django 5.2.16 on 2026-07-28 15:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0010_remove_newspage_summary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("article_image", 5),
                    ("table", 6),
                    ("youtube", 7),
                    ("spotify", 8),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "h2",
                                "h3",
                                "h4",
                                "ol",
                                "ul",
                                "blockquote",
                                "hr",
                                "document-link",
                            ],
                            "label": "Párrafo",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Imagen"},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Pie de foto"}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": (
                                "Describe el sentido contextual de esta imagen "
                                "en la noticia."
                            ),
                            "label": "Texto alternativo",
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Crédito de imagen", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("caption", 2),
                                ("alt_text", 3),
                                ("credit", 4),
                            ]
                        ],
                        {},
                    ),
                    6: ("apps.news.blocks.NewsTableBlock", (), {}),
                    7: ("apps.news.blocks.YouTubeEmbedBlock", (), {}),
                    8: ("apps.news.blocks.SpotifyEmbedBlock", (), {}),
                },
                verbose_name="Contenido",
            ),
        ),
    ]
