# Generated by Django 5.2.15 on 2026-07-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Página de inicio', 'verbose_name_plural': 'Páginas de inicio'},
        ),
    ]
