# Generated by Django 5.2.16 on 2026-07-13 23:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_options'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(help_text='Resume el propósito de esta página en uno o dos párrafos breves.', max_length=400, verbose_name='Introducción')),
                ('body', wagtail.fields.RichTextField(help_text='Usa subtítulos, enlaces, listas y citas para organizar contenido institucional sencillo.', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Página institucional',
                'verbose_name_plural': 'Páginas institucionales',
            },
            bases=('wagtailcore.page',),
        ),
    ]
